# Intermediate Python 

Welcome back! This notebook picks up where **Intro to Python** left off. It assumes you're
comfortable with: variables, numbers, strings, lists, dictionaries, `if`/`elif`/`else`, and writing simple functions.  

Topics to be covered:  

1. JupyterLab's built-in **visual debugger** (point-and-click,
   no typed commands), used throughout this notebook
2. **Watching your data types as you go** — one of the most common sources of bugs in
   real code is assuming a variable is one type (a string) when it's actually another
   (a list, a view, an iterator) — we'll practice catching this
3. **Tuples and sets** — two more built-in collection types
4. **List comprehensions** — a compact way to build lists
5. **String formatting and file I/O** — getting data in and text out
6. **Classes** — defining your own custom data types (a big topic in "real" Python code)


A short **Further Study** section is included at the end (inheritance, pickling, custom
iterators) for anyone who wants to keep going after class — we likely will not get to those subjects.
<br>
<br>

# A few words regarding Jupyter notebook

### Working with cells in JupyterLab

- **Edit mode:** Press **Enter** or click inside a cell to edit its code or text.
- **Command mode:** Press **Esc** to work with whole cells. Press **A** to insert a cell above, **B** to insert one below, or **D twice** to delete the selected cell.
- **Command palette:** Open it using the shortcut below, type an action such as “Restart Kernel,” and select it.

| Action | Mac | Windows |
|---|---|---|
| Run cell and move to the next | Shift + Enter | Shift + Enter |
| Run cell and stay on it | Cmd + Enter | Ctrl + Enter |
| Run cell and insert one below | Option + Enter | Alt + Enter |
| Open command palette | Cmd + Shift + C | Ctrl + Shift + C |
| Undo text edit (edit mode) | Cmd + Z | Ctrl + Z |
| Redo text edit (edit mode) | Cmd + Shift + Z | Ctrl + Shift + Z |
| Undo cell operation, such as deletion (command mode) | Z | Z |
| Redo cell operation (command mode) | Shift + Z | Shift + Z |

Running a **code cell** executes Python; running a **Markdown cell** displays its formatted text. Undo changes text or cell operations; it does not reverse executed Python code.

## The Notebook, Multiple Outputs & the JupyterLab Visual Debugger

First, hopefully everyone is familiar with working on a server.

#### Where is this computing happening anyway?:  
- The interplay between your laptop, the server system, and their directory structures.
- Working on the command line
- Saving files from the server to your laptop
- Uploading from your laptop to the server

### Run the cell below cell to activate multi-output functionality

In [16]:

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
# Check that these two lines create output on two lines
2 + 2
3 * 3

4

9

### Jupyterlab debugger

### How to turn it on

1. Make sure you're running this notebook in **JupyterLab** (not the older "classic"
   Notebook interface) with a kernel that supports debugging (`ipykernel` version 6.9+ —
   most modern installs already have this).
2. Look at the **top-right corner of the notebook**. If your kernel supports it, you'll
   see a small **bug icon**. Click it to turn the debugger **on**.
3. Once it's on, a **Callstack / Variables / Breakpoints** panel appears in the right
   sidebar.
4. Also, **Show line numbers** will be turned on within the cell, so you can click in the left margin next to a line to set a
   **breakpoint** — a red dot will appear. This is the first thing you should do -- set a breakpoint.
5. Click inside the cell, and run the cell (`Shift + Enter`) as normal. Execution will **pause** at your breakpoint,
   and the **Variables panel** will show you the current value of every variable in
   scope — updated live as you step.
6. Use the step controls in the sidebar (Continue, Step Over, Step In, Step Out,
   Terminate) to move through the code one line — or one function call — at a time.

### 🧪 Try it: get comfortable with the controls

Show line numbers on the cell below, click in the margin next to the `total = total + i`
line to set a breakpoint, turn the debugger on, then run the cell. Use **Step Over**
repeatedly and watch `total` and `i` change in the Variables panel. Then click
**Continue** to let it finish.

In [25]:
total = 0
for i in range(10):
    total = total + i
print("Final total:", total)

Final total: 45

## 1. Quick Recap: Data Types

A short reminder of the basic types from the intro course

In [3]:
# The basics from last time
an_int = 42
a_float = 3.14
a_string = "ATGC"
a_list = ["A", "T", "G", "C", a_float]
a_dict = {"A": "Adenine", "T": "Thymine", "G": "Guanine", "C": "Cytosine", a_float: a_list}
a_bool = True

print("---------")

for element in [an_int, a_float, a_string, a_list, a_dict, a_bool]:
    print(f"{element} -> {type(element)}")

---------
42 -> <class 'int'>
3.14 -> <class 'float'>
ATGC -> <class 'str'>
['A', 'T', 'G', 'C', 3.14] -> <class 'list'>
{'A': 'Adenine', 'T': 'Thymine', 'G': 'Guanine', 'C': 'Cytosine', 3.14: ['A', 'T', 'G', 'C', 3.14]} -> <class 'dict'>
True -> <class 'bool'>

### String and List Methods

A **method** is an operation associated with an object. Call it using a dot after the object: `object.method(arguments)`.

#### String methods

Strings are **immutable**: these methods return a result without changing the original string.

| Method | What it does | Example | Result |
|---|---|---|---|
| `.count()` | Counts occurrences of a substring | `"banana".count("an")` | `2` |
| `.upper()` | Converts letters to uppercase | `"Hello".upper()` | `"HELLO"` |
| `.lower()` | Converts letters to lowercase | `"Hello".lower()` | `"hello"` |
| `.strip()` | Removes whitespace from both ends | `"  hello \n".strip()` | `"hello"` |
| `.replace()` | Replaces occurrences of a substring | `"banana".replace("a", "o")` | `"bonono"` |
| `.find()` | Returns the index of the first match, or `-1` if absent | `"banana".find("na")` | `2` |

String indices start at **0**, and matching is **case-sensitive**.

To keep a modified string, assign the result to a variable:

```python
sequence = "  atgc  "
sequence = sequence.strip().upper()
print(sequence)  # ATGC
```

#### List methods

Lists are **mutable**: these methods change the original list object.

Each example below starts with the list: `numbers = [3, 1, 2, 1]`.

| Method | What it does | Example | List afterward |
|---|---|---|---|
| `.append()` | Adds one item to the end | `numbers.append(4)` | `[3, 1, 2, 1, 4]` |
| `.pop()` | Removes and returns an item; defaults to the last | `numbers.pop()` | `[3, 1, 2]` |
| `.remove()` | Removes the first occurrence of a value | `numbers.remove(1)` | `[3, 2, 1]` |
| `.reverse()` | Reverses the current order | `numbers.reverse()` | `[1, 2, 1, 3]` |
| `.sort()` | Sorts items in ascending order | `numbers.sort()` | `[1, 1, 2, 3]` |

- Use `.pop(index)` to remove an item by **position**.
- Use `.remove(value)` to remove an item by **value**. It raises an error if the value is absent.
- Use `.sort(reverse=True)` to sort in descending order.
- Except for `.pop()`, these list methods return `None`. Call them directly rather than assigning their result back to the list.

```python
numbers = [3, 1, 2]
numbers.sort()
print(numbers)  # [1, 2, 3]

last_item = numbers.pop()
print(last_item)  # 3
print(numbers)    # [1, 2]
```

### 🧪 Try it yourself

1. Create a string containing a DNA sequence with lowercase and uppercase letters and spaces at both ends.
2. Use a single command to remove the surrounding spaces, convert it to uppercase, and count its `"G"` characters.
3. Replace each `"T"` with `"U"` and find the index of the first `"A"`.
4. Create a list of numbers 'a_list'. Append a number, and pop an element.
5. Sort the list, then reverse it.
6. Can 4 and 5 be done in one command? Any explanation?

In [53]:
a_string = " ACGgcTcGTTTCAA "

a_list = list(range(1,11))

### -Boolean operators: `and`, `or`, `not`
`True` and `False` are the only two `bool` values.  
Comparisons (`==`, `<`, `in`, ...) always produce a `bool`, and `bool`s combine with logical operators  
like `and`, `or`, `not` to produce more complex logical statements.

#experiment with boolean operators below. Ad an elif statement so that the code prints some response

Write an `if` / `elif` statement that prints:

- `"A"` if `x` is greater than 10 **and** divisible by 3. (10 modulo 3 is equal to zero)
- `"B"` if `x` is greater than 5 **or** divisible by 2.
- `"C"` if `x` is less than or equal to 5.

In [ ]:
x = 5
if . . . :
    print("A")
.
.
.

In [35]:
is_dna = "ATGC".isalpha()
print(is_dna, type(is_dna))
print(not is_dna)
print(is_dna and len("ATGC") == 4)

True <class 'bool'>
False
True

In [ ]:
dna = "ATACgcAATGCCCACGatacCGGACTACTGCATAAAAAAAA"

# Your code here
dna_upper = ...
g_count = ...
c_count = ...
gc_content = ...
print(gc_content)

## 2. Nested `for` Loops, Revisited — Debugger Practice

A nested loop is a loop inside another loop). Here's a
slightly trickier one, plus a chance to use the **visual debugger** to verify your logic instead of just guessing. Printing output can also be a way to debug -- there are a couple of print statements to suggest how you might do that (but we're using the debugger!).

**The task:** for every combination of temperature, rain, and fog status below, print
`"going for a hike"` if the weather is good (temperature above 15 **and** it is not
raining or foggy), otherwise print `"bad weather"`.

In [15]:
temp = [2, 10, 16, 40]
raining = [True, False]
foggy = [True, False]

for i in temp:
    for j in raining:
        for k in foggy:
            if i > 15 and not (j or k) :      # <--  verify this condition
                print("going for a hike")
                #print(f"temp={i}, raining={j}, foggy={k}: going for a hike")
            else:
                print("bad weather")
                #print(f"temp={i}, raining={j}, foggy={k}: bad weather")

bad weather
bad weather
bad weather
bad weather
bad weather
bad weather
bad weather
bad weather
bad weather
bad weather
bad weather
going for a hike
bad weather
bad weather
bad weather
going for a hike

### 🧪 Try it: verify with the debugger

Instead of trusting that 'going for a hike' is printed only at the correct iterations, we can verify using the debugger. Show line numbers on the
cell above, set a breakpoint on the `if i > 15 and not j:` line, turn the debugger on,
and re-run the cell.

- Use **Step Over** to advance one line at a time.
- After each pause, check the **Variables panel**: what are the current values of `i`
   `j` `k`? Do they match what you expect for that point in the nested loop?
- Next, set another break point at the line where 'going for a hike' is printed.  Click the **Continue** icon in the debugger 'calls' section to jump to that next break point.

## 3. Dictionaries Revisited: Iterating & Watching Your Data Types

Dictionaries are everywhere in real code, and they're also where A LOT of bugs sneak in
— usually because a value isn't the type you assumed it was. This section is as much
about the **habit of checking `type()`** as it is about dictionary syntax.

### Quick syntax refresher

In [ ]:
motifs = {"CEBPD": ["ATGC"], "BRCA1": ["CAGA"], "ATF1": ["ATCC"], "IRF1": ["ATTAACC"]}
motifs

In [ ]:
# Accessing a value by its key (like list access, but with a key instead of a position)
motifs["BRCA1"]

In [ ]:
# Updating a dictionary -- add a new key, or overwrite an existing one
motifs["NEW_TF"] = ["GGGG"]
motifs

# Deleting an entry
del motifs["NEW_TF"]
motifs

#### `.keys()`, `.values()`, `.items()` — and what type do they *really* return?

It's tempting to assume that the  `.keys() .values() .items()` methods return lists, because you can iterate over them. Let's check.

In [21]:
motifs = {"CEBPD": ["ATGC"], "BRCA1": ["CAGA"], "ATF1": ["ATCC"], "IRF1": ["ATTAACC"]}

k = motifs.keys()
print(type(k))     # not a list!

v = motifs.values()
print(type(v))      # not a list either

i = motifs.items()
print(type(i))

<class 'dict_keys'>
<class 'dict_values'>
<class 'dict_items'>

`.keys()`, `.values()`, and `.items()` all return special **"view" objects**, not lists.
A view is a **live**, read-only window into the dictionary — if the dictionary changes
later, anything holding onto that view changes too, automatically.

In [5]:
beatles_directory = {
    "Guitar": "John",
    "Lead Guitar": "George",
    "Bass": "Paul",
    "Drums": "Ringo",
}

# Save the items view to a variable
saved_items = beatles_directory.items()
print("Before:", saved_items)

# Now change the dictionary...
beatles_directory["Guitar"] = ["John", "George"]
del beatles_directory["Lead Guitar"]

# ...and the "saved" view has changed too, even though we never 'touched it' directly!
print("After: ", saved_items)

Before: (('Guitar', 'John'), ('Lead Guitar', 'George'), ('Bass', 'Paul'), ('Drums', 'Ringo'))
After:  (('Guitar', 'John'), ('Lead Guitar', 'George'), ('Bass', 'Paul'), ('Drums', 'Ringo'))

**takeaway:** if you want a frozen snapshot of a dictionary's keys/values/items to use
later, convert it to a `list` right away: `list(my_dict.items())`. If keeping that snapshot unchanged is very important, consider a tuple. Developers use tuples in Python to safeguard data against accidental alteration and to signal to collaborators that a collection should remain constant

### Iterating over a dictionary

In [23]:
#Here is a dictionary, but let's make it much more functional by using lists.

motifs = {"CEBPD": "ATGC", "BRCA1": "CAGA", "ATF1": "ATCC", "IRF1": "ATTAACC"}

# Iterating with just the keys
for gene in motifs:
    print(gene)

print("---")

# Iterating with .items() gives you both key and value together -- the most common pattern
for gene, motif in motifs.items():
    print(f"{gene} -> {motif}")

#f-string to achieve the same thing

CEBPD
BRCA1
ATF1
IRF1
---
CEBPD -> ATGC
BRCA1 -> CAGA
ATF1 -> ATCC
IRF1 -> ATTAACC

#### `.pop()` — remove a key and get its value back in one step
What would be a good use case for .pop() with a dictionary (or list)?

In [2]:
motifs = {"CEBPD": ["ATGC"], "BRCA1": ["CAGA"], "ATF1": ["ATCC"], "IRF1": ["ATTAACC"]}

removed_value = motifs.pop("ATF1")
print(removed_value)
print(motifs)

['ATCC']
{'CEBPD': ['ATGC'], 'BRCA1': ['CAGA'], 'IRF1': ['ATTAACC']}

### Biology Application: Finding Transcription Factor Motifs

**task**: given a DNA sequence and a dictionary of transcription factor (TF) binding
motifs, use an accumulator and a for loop to find which motifs are present in the sequence, and collect the keys in a list called 'hits'.  
<br>
**more advanced**: Do the same as above, but remove the hits from the dictionary with each iteration. Put it in a function if you can.

In [6]:
seq = "ATTtAACCATCAGAATCCACAgAcaTTaCNNACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAAtCC"

motifs = {
    "CEBPD": "ATGC",
    "BRCA1": "CAGA",
    "ATF1": "ATCC",
    "IRF1": "ATTAACC"
}

# We first need an empty list (accumulator)
hits = list() # or simply hits = []

## 4. Tuples, and zip()

A **tuple** looks like a list, but written with parentheses `()` instead of square
brackets.  
Unlike lists, tuples are **immutable**: once created, the tuple object itself can't be changed.

In [9]:
beatles = ("John", "Paul", "George", "Pete")
print(beatles)
print(beatles[0])     # indexing works just like a list
print(beatles[1:3])   # so does slicing

('John', 'Paul', 'George', 'Pete')
John
('Paul', 'George')

In [49]:
# But you can't change it... try to change 'Pete' to 'Ringo' below



#dir(tuple)

### Why use something you can't change?

- Sometimes you *want* a guarantee that something won't accidentally be modified later
  in your code.
- Mistakes in code can lead to silent changes can with lists.
- Functions that return **more than one value** actually return a tuple, e.g.
  `return x, y` packs `x` and `y` into a tuple automatically.
- `zip()` produces tuples (we'll see this below).
- Dictionary `.items()` gives you tuples of `(key, value)` pairs, as you just saw in
  Section 3.

In [15]:
def min_and_max(numbers):
    return min(numbers), max(numbers)     # returns a tuple

listOnumbers = [4, 8, 15, 16, 23, 42]

result = min_and_max(listOnumbers)
print(result, type(result))

low, high = result       # "unpacking" the tuple into two variables using a 'Pythonic' shortcut
print(low, high)

(4, 42) <class 'tuple'>
4 42

### `zip()` produces an **iterator**, not a list

This is another good example of "don't assume the type" — `zip()` looks like it
gives you a list of tuples, but it actually gives you an `iterator` that you have to pull
values from one at a time (or convert to a list).

In [7]:
letters = ["a", "b", "c"]
numbers = [1, 2, 3]
zipped = zip(letters, numbers)

#write a for loop below to print the elements in 'zipped'

In [ ]:
# zipped
# print(type(zipped))          # an iterator, not a list!

# print(next(zipped))
# print(next(zipped))
# print(next(zipped))
# # next(zipped) here would raise StopIteration -- nothing left

#### The usual fix: wrap it in list() right away if you want to keep using it.

In [28]:
zipped_list = list(zip(letters, numbers))
print(zipped_list)

[('a', 1), ('b', 2), ('c', 3)]

### 🧪 Try it yourself
`zip()` stops at the length of the **shortest** input. Given the two lists below,
predict what `list(zip(...))` will produce.

In [14]:
short_list = [1, 2, 3]
long_list = ["a", "b", "c", "d", "e"]

# Your prediction:
#
# Check it:

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

## Is zip() really *that* useful? . . . YES!

In [39]:
from pandas import DataFrame


gene_names = ['CEBPD', 'BRCA1', 'ATF1', 'IRF1']
values = [['ATGC', "AACC"], ['CAGA', "TTCC"], ['ATCC', 'ACGT'], ['ATTAACC', 'CCGG']]
#values = [1,2,3,4]

#zip plays nicely with dict
dict(zip(gene_names, values))

print('\n-------\n\n')

#dict plays nicely with pandas dataframes
DataFrame.from_dict(dict(zip(gene_names, values)))

{'CEBPD': ['ATGC', 'AACC'],
 'BRCA1': ['CAGA', 'TTCC'],
 'ATF1': ['ATCC', 'ACGT'],
 'IRF1': ['ATTAACC', 'CCGG']}

-------

  CEBPD BRCA1  ATF1     IRF1
0  ATGC  CAGA  ATCC  ATTAACC
1  AACC  TTCC  ACGT     CCGG

In [12]:
#Zip the two lists below together 
#convert to a dictionary, then to a dataframe

list1 = ["Name", "Age", "City"]
list2 = [ ['Alice', 'Bob', 'Charlie'], [25, 30, 35], ['New York', 'London', 'Paris'] ]

## 5. Sets

A **set** stores **unique** values with no particular order, and supports the same
logical operations as in math class: union, intersection, difference, subset.

In [1]:
visited = {"USA", "USA", "Mali", "Mexico", "Canada", "France", "Japan"}
print(visited)     # duplicates are automatically dropped
print(type(visited))

{'Japan', 'Mali', 'USA', 'Mexico', 'Canada', 'France'}
<class 'set'>

Below a set is created from a list.
Look at the directory for the data type set, and find the method to add a member to a set.  
Add Germany, and try adding it again. What happens?

In [14]:
visited = set(["USA", "Canada", "Mexico", "France", "Japan"])

### Set operations

In [ ]:
europe = {"England", "France", "Italy", "Germany", "Spain", "Poland"}
americas = {"USA", "Canada", "Mexico"}

print("Intersection (visited AND in Europe):", visited & europe)
print("Union (Europe OR the Americas):       ", europe | americas)
print("Difference (visited, but NOT Europe/Americas):", visited - (europe | americas))
print("Is {'England','Italy'} a subset of Europe?", {"England", "Italy"} <= europe)

### A very common trick: de-duplicating a list

Converting a list to a `set` and back to a `list` is the standard way to get the unique
elements of a list.

In [ ]:
raw_bases = ["A", "T", "G", "G", "C", "C", "C", "A", "T"]
unique_bases = list(set(raw_bases))
print(unique_bases)

### 🧪 Try it yourself
Given two sets of gene names below, find:
1. The genes present in **both** experiments (intersection)
2. The genes present in the control **but not** the treatment (difference)

In [57]:
control_genes = {"TP53", "BRCA1", "MYC", "EGFR", "KRAS"}
treatment_genes = {"TP53", "MYC", "PTEN", "ATM"}

# Your code here
in_both = 
only_in_control = 
print(in_both)
print(only_in_control)

{'TP53', 'MYC'}
{'BRCA1', 'EGFR', 'KRAS'}

### Biology Application: Finding Transcription Factor Motifs  
#### More advanced: what if a motif occurs *more than once*?

Let's count occurrences with `.count()`, and store each result as a `(sequence, count)`
tuple in a dictionary.

One entry in the dictionary: {'CDBPD': ('ATGC', 3), . . . }

In [62]:
seq = "ATTtAACCATCAGAATCCACAgAcaTTaCNNACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAAtCC"

motifs = {
    "CEBPD": "ATGC",
    "BRCA1": "CAGA",
    "ATF1": "ATCC",
    "IRF1": "ATTAACC"
}
hit_counts = {}

for gene, motif in motifs.items():
    n = seq.upper().count(motif)
    if n > 0:
        hit_counts[gene] = (motif, n)

print(hit_counts)

{'CEBPD': ('ATGC', 3), 'BRCA1': ('CAGA', 4), 'ATF1': ('ATCC', 2)}

## 6. List Comprehensions

A **list comprehension** is a compact way to build a list from a loop, in a single
line: `[expression for item in iterable]`.

In [64]:
# The "long way", with a regular for loop:
evens = []
for n in range(1, 21):
    if n % 2 == 0:
        evens.append(n)
print(evens)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [66]:
# The same thing as a list comprehension:
evens = [n for n in range(1, 21) if n % 2 == 0]
evens

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
# Squares of the first 10 integers
squares = [n ** 2 for n in range(10)]
print(squares)

# Squares of even numbers only, up to 15
even_squares = [n ** 2 for n in range(15) if n % 2 == 0]
print(even_squares)

### Comprehensions work on any iterable object: strings, lists, dictionaries, tuples, sets

In [ ]:
nested = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12, 13, 14]]

# Pull out just the first element of each sub-list
first_elements = [sub_list[0] for sub_list in nested]
print(first_elements)

# Add a condition: only keep first elements that are even
even_firsts = [sub_list[0] for sub_list in nested if sub_list[0] % 2 == 0]
print(even_firsts)

In [72]:
# A dictionary comprehension

list_a = ['a', 'b', 'c', 'd', 'e']
list_b = [1,2,3,4,5]

new_dict = {i: j for i,j in zip(list_a, list_b)}
new_dict

newer_dict = {i: j for i,j in zip(list_a, list_b) if j < 4 }
newer_dict

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

{'a': 1, 'b': 2, 'c': 3}

### 🧪 Try it yourself
1. Use a list comprehension to build a list of the **cubes** of every integer from 1 to
   20 whose cube is **less than 5,000**.
2. Using the `motifs` dictionary from above, use a list comprehension to build a
   list containing ONLY the gene names (keys) whose motif is **longer than 4 characters**.

In [ ]:
# Part 1
cubes_under_5000 = ...
print(cubes_under_5000)

In [ ]:
# Part 2
motifs = {
    "CEBPD": "ATGC",
    "BRCA1": "CAGA",
    "ATF1": "ATCC",
    "IRF1": "ATTAACC"
}

### 🧪 Try it yourself
The loop we worked with above is replicated below. Rewrite the loop as a **list comprehension** that builds the same `(gene, count)` tuple list, but **only** for
genes with 2 or more hits. Store the tuples in a list called 'hits2'.  
<br>
If that goes well, store the same information in some kind of dictionary using a dictionary comprehension.  
<br>

In [80]:
seq = "ATTtAACCATCAGAATCCACAgAcaTTaCNNACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAAtCC"
motifs = {"CEBPD": "ATGC", "BRCA1": "CAGA","ATF1": "ATCC", "IRF1": "ATTAACC"}

hits = []
for gene, motif in motifs.items():
    if motif in seq.upper():
        count = seq.upper().count(motif)
        hits.append((gene, count))
print("Motifs found:", hits)

#Write list comprehension code below:

#hits2 = . . . 
#hits2

Motifs found: [('CEBPD', 3), ('BRCA1', 4), ('ATF1', 2)]


## 7. Coding practice: Functions

### Function 1. Place the hits loop above in a function and call it on the dictionary
-Write a docstring for the function!

In [24]:
def get_hits():
    '''
    This is a docstring. inputs: ; outputs: 
    '''
    pass
    
?get_hits

Signature: get_hits()
Docstring: This is a docstring.
File:      /tmp/ipykernel_2281632/2377809260.py
Type:      function

### Function 2. Find the location(s) (indice(s)) of one transcription factor motif in the given sequence.
Start with a simple case -- pick one binding sequence and figure out how to write code for that.  
Next, transfer that code into a function that will work on any input sequence.   
Again, first consider inputs, outputs.  
Hint: The typical algorithm is a 'sliding window'; Question: What if a sliding window slides off the end of a sequence?

In [5]:
seq = "ATTAACCATCAGAATCCACAgAcaTTaCNNACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACCCAGA"
query = "CAGA"
len(seq)

99

In [6]:
indx_hits = []
for index in range(??):
    .
    .
    .

[9, 18, 72, 81, 95]

### Function 3. Make a function that calls the above function to operate on all TF genes in the dictionary
- Find all starting indices of all genes in the dictionary, and collect them in a dictionary (keys = gene names, values = list of indices).
- Call the function you created above from within your new function!  
- More advanced: Find start AND end indices (dictionary values are lists with tuples as elements:`(start_loc, end_loc)`.

In [ ]:
seq = "ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC"
motifs = {"CEBPD" : "ATGC",
          "BRCA1" : "CAGA",
          "ATF1" : "ATCC",
          "IRF1" : "ATTAACC"}

### ⚠️ Now let's break something on purpose

Here's code that should function properly, and does, with the exception of one error. Find the error using the debugger!  
Notice Scoping within functions!

In [40]:
seq = "ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC"
motifs = {"CEBPD" : "ATGC",
          "BRCA1" : "CAGA",
          "ATF1" : "ATCC",
          "IRF1" : "ATTAACC"}

def get_hits(bind_seq, sequence):
    out_list = []
    for i in range(0,len(seq)):
        if bind_seq == sequence[i:i+4].upper():
            out_list.append(i)
    return out_list
    
def get_indices(query_arg, seq_arg):
    '''
    inputs: str, str; outputs: list.
    '''
    indices = []
    for i in range(len(seq_arg)):
        if seq_arg.upper()[i:i+4] == query_arg:
            indices.append(i)
        
    return indices  
    
def analyze_dict(dict_arg, seq_arg):
    '''
    inputs: dictionary, sequece; output: dictionary (key: str, value: list)
    '''
    out_dict = {}
    for key, value in dict_arg.items():
        hits = get_indices(seq_arg, value)
        out_dict[key] = hits
    return out_dict

hit_dict = analyze_dict(motifs, seq)
hit_dict

{'CEBPD': [], 'BRCA1': [], 'ATF1': [], 'IRF1': []}

## 8. Reading lines from a file

### To read lines from a file, we first have to find out where the file is in the directory structure.  
To the command line!!

In [11]:
import os
os.getcwd()

'/stor/home/mbramble/TEACHING/short_courses/intermed_python_fall_2026'

In [25]:
filePath = '/stor/home/mbramble/TEACHING/short_courses/intermed_python_fall_2026/sequences.txt'
with open(filePath, "r") as file:
    
    file_lines = []
    for line in file:
        sequence = line.strip()
        file_lines.append(sequence)
    #perhaps a list comprehension is in order?]
file_lines

['ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'AaTTaAAaCCaATaCAaGAaATaCCaACaAgaAcaaTaTaaCNnACaTACAaGGGtaATaGCcCAATaGCTAGaCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC',
 'ATTAACCATCAGAATCCACAgAcaTTaCNnACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAACC']

### 🧪 Function 4: Read sequences from a file and search for motifs

The file `sequences.txt` contains **one DNA sequence per line**.

The following function reads the file and runs the function we've been working on on each sequence.

1. Read the code and try to understand what is happening.
2. Rewrite the line-reading code using a list comprehension.
3. (Advanced) Rewrite the dictionary construction code using a dict method (you will need to figure out how to get keyword names into your dict comprehension (hint: use zip!)).


Before starting, make sure `get_hits()` uses the length of its `sequence`
argument and the length of the motif, rather than the global `seq` and
a fixed four-character window.

In [26]:
def analyze_sequence_file(motif_dict, filename):
    """Read sequences from a file and return motif hits for each sequence."""
    results = {}

# Line-reading code
    with open(filename, "r") as file:
        file_lines = []
        for line in file:
            sequence = line.strip()
            file_lines.append(sequence)
# 
    sequence_name_suffix = 1
    for seqo in file_lines:
        sequence_name = f"seq{sequence_name_suffix}"
        results[sequence_name] = analyze_dict(motif_dict, seqo)
        sequence_name_suffix += 1
    return results


results = analyze_sequence_file(motifs, "/stor/home/mbramble/TEACHING/short_courses/intermed_python_fall_2026/sequences.txt")
results

{'seq1': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq2': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq3': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq4': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq5': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq6': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq7': {'CEBPD': [80], 'BRCA1': [91, 100], 'ATF1': [], 'IRF1': []},
 'seq8': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq9': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq10': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq11': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq12': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq13': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq14': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []},
 'seq15': {'CEBPD': [41, 48, 61],
  'BRCA1': [9, 18, 72, 81],
  'ATF1': [13],
  'IRF1': []}}

## 9. Default Arguments & `*args`

### Default arguments and positional vs. keyword arguments

A **default argument** lets you call a function without specifying every parameter.
Below, `gene` defaults to `"BRCA1"` if the caller doesn't provide one.

In [ ]:
def get_indices_BRCA1(sequence, motif_dict, gene="BRCA1"):
    
    motif = motif_dict[gene]
    seq_upper = sequence.upper()
    hits = []
    for i in range(len(seq_upper) - len(motif) + 1):
        if seq_upper[i:i + len(motif)] == motif:
            hits.append(i)
    return hits


print(get_indices(seq, motifs))                  # uses the default gene="BRCA1"
print(get_indices(seq, motifs, "IRF1"))           # positional argument
print(get_indices(seq, motifs, gene="IRF1"))      # keyword argument -- same result

### `*args` `**kwargs` — functions that accept any number of arguments

Sometimes you don't know in advance how many arguments a function will need. `*args`
collects any number of positional arguments into a tuple. Here's a version of `zip`
that, unlike the real one, pads shorter lists with `"NA"` instead of stopping early.

In [38]:
def zip_padded(*args):
    """Zip any number of lists, padding shorter lists with 'NA'."""
    max_length = max((len(lst) for lst in args), default=0)

    padded_lists = []
    for one_list in args:
        padded = one_list + ["NA"] * (max_length - len(one_list))
        padded_lists.append(padded)

    return list(zip(*padded_lists))


# Example
a = [1, 2, 3, 4, 5]
b = [4, 7]
c = [5, 6, 6]

zip_padded(a, b, c)

[(1, 4, 5), (2, 7, 6), (3, 'NA', 6), (4, 'NA', 'NA'), (5, 'NA', 'NA')]

In [39]:
def calculate_total(**kwargs):
    """Return the total cost of any number of named expenses."""
    total = 0
    for expense, cost in kwargs.items():
        print(f"{expense}: ${cost:.2f}")
        total += cost
    return total


total_cost = calculate_total(travel=125, meals=45, supplies=30)
print(f"Total: ${total_cost:.2f}")

travel: $125.00
meals: $45.00
supplies: $30.00
Total: $200.00

### Reading files, line by line

The standard pattern for reading a file uses `with open(...) as f:`, which
automatically closes the file when you're done — even if an error happens partway
through.

Let's first create a small sample file so this notebook is self-contained (in your own
projects, this file would already exist — e.g. a `.fasta` or `.fastq` file of real
sequencing reads).

In [ ]:
sample_sequences = [
    ">read1",
    "ATGCGGATCCTTAACGGGCTA",
    ">read2",
    "GGGCCATTAGCATGACGGTTA",
    ">read3",
    "TTACGATCGATCGGGCTAATT",
]

with open("sample_sequences.fa", "w") as file_out:
    for line in sample_sequences:
        file_out.write(line + "\n")

print("Sample file written.")

In [ ]:
# Now read it back, line by line
with open("sample_sequences.fa", "r") as file_in:
    line_list = [line for line in file_in]

print(line_list)

Notice each line still has a trailing `"\n"` (newline) character. `.strip()` will remove
leading/trailing whitespace, including newlines.  
Fix the code above in the cell below using .strip()

### 🧪 Try it yourself
Using the same file, write a list comprehension that gathers **only the sequence
lines** (skip the lines starting with `">"`) into a list called `sequences_only`. You may have to look through the dir() to find a method that detects the starting characters of a string.

In [ ]:
# Your code here
sequences_only = ...



print(sequences_only)

### **Further study:** 
The standard library modules `pickle` and `shelve` let you save
Python objects (large lists, dicts, dataframes) directly to disk and reload
them later, without converting to text or tables.
We won't cover them today, but they're easy to use and very convenient for storing data results.

## 9. String Formatting & File I/O

### f-strings, `.format()`, and numeric formatting

You've already used f-strings. Here's a quick reminder plus the older `.format()`
style you'll still see in other people's code, and how to control decimal places.

In [ ]:
num_pigs = 2
num_horses = 4

# f-strings (preferred, modern style)
print(f"{num_pigs} pigs in the sty, {num_horses} horses in the barn.")

# .format() -- functionally equivalent, seen often in older code
print("{} pigs in the sty, {} horses in the barn.".format(num_pigs, num_horses))

In [ ]:
import math

pi_approx = math.pi
print(f"Pi is approximately {pi_approx:.2f}")      # 2 decimal places
print(f"Pi is approximately {pi_approx:.4f}")       # 4 decimal places
print(f"Pi + Pi = {pi_approx + pi_approx:.3f}")     # you can put an expression inside {}

In [ ]:
# Advanced exercise

# Biological scenario; dictionary exercise
Move transcription factors into a new list, but in the new list, 
use a single entry for each gene name. in this new 'hits' dictionary, the values will be lists (so that you can add to the values).  
For example {CEBPD: ["ATGC", "ACTA"]}  
Note: you can't iterate over motif.items() and change the dictionary inside the for loop (because motif.items() is a window type object). You have to first place dict.items() in a list type object, and then iterate over that list.

In [38]:
seq = "ATTtAACCATCAGAATCCACAgAcaTTaCNNACTACAGGGtaATGCcCAATGCTAGCCAACAATGCGAATCAGCAGAACACACAGATaaATTAAtCC"

hits = {}
motifs = {
    "CEBPD.1": "ATGC",
    "CEBPD.2": "ACTA",
    "BRCA1": "CAGA",
    "ATF1": "ATCC",
    "IRF1": "ATTAACC",
}

## File I/O Working with files
Read the code below, and figure out what is going on.
You will have to go to the command line and look at the original file to understand how the code works. The debugger will help here to look at the variables in each iteration.

In [ ]:
import os
os.chdir('/stor/home/mbramble/TEACHING/short_courses/intermed_python_fall_2026')
os.listdir()

In [31]:
import csv
# Import only the required class
from pandas import DataFrame 

measurement_names = ["fine", "medium", "large"]
samples = {}

with open("particulates.csv") as file:
    next(file)
    
    for row in csv.reader(file):
        sample_name = row[0]
        measurements = [float(value) for value in row[1:]]

        samples[sample_name] = dict(zip(measurement_names, measurements))
display(DataFrame(samples).transpose())

                           fine  medium  large
Atlanta_GA_2026-09-01      7.81    9.77   5.12
Atlanta_GA_2026-09-02      7.10   11.05   3.98
Atlanta_GA_2026-09-03      6.73    7.02   5.31
Atlanta_GA_2026-09-04     14.07    9.22   5.18
Atlanta_GA_2026-09-05      6.90    5.64   3.30
...                         ...     ...    ...
Washington_DC_2026-09-21   7.53    5.93   5.65
Washington_DC_2026-09-22   5.12    5.33   4.44
Washington_DC_2026-09-23   6.48    8.26   3.61
Washington_DC_2026-09-24   5.67   13.35   9.02
Washington_DC_2026-09-25   7.70    8.03   8.32

[500 rows x 3 columns]

### Advanced: flattening a nested list

A list comprehension can loop over more than one level at once — handy for
"flattening" a list of lists (of lists...) into one flat list. The syntax is difficult because the comprehension works through the levels in the opposite order you might expect.

In [48]:
level_1 = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9, 10, 11, 12]]]

flat = [number*2 for level_2 in level_1 for level_3 in level_2 for number in level_3]
print(flat)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]

# Advanced exercises: Answers

In [ ]:
# Biological scenario

In [ ]:
iter = 0
for key, value in list(motifs.items()):
    gName = key.split('.')[0]
    if value in seq:
        if gName in hits:
            hits[gName].append(value)
        else: hits[gName] = [value]
    del motifs[key]
hits
motifs

## 10. Intro to Classes: Modeling a DNA Sequence

### Why classes?

Imagine representing each sequencing read as a dictionary:

```python
brain_seq1 = {"sequence": "ACGTTGAC", "quality": 27, "length": 8}
brain_seq2 = {"sequence": "TTTACGAC", "quality": 31, "length": 8}
# ...repeat for every read...
```

This works, but it's repetitive, and it treats each read as "just data" rather than as
a *thing* with behavior (reverse-complementing, comparing, combining). A **class** lets
you define your own custom type — like `int`, `str`, or `list`, but built for your
problem. An **object** created from a class is called an **instance** of that class.

### Defining a class

In [ ]:
class Sequence:
    tissue = "brain"          # a "class attribute" -- shared by every instance

    def __init__(self, seq, quality):     # runs automatically when you create an instance
        self.seq = seq
        self.qual = quality
        self.len = len(self.seq)

In [ ]:
# Create two instances of our new class
seq1 = Sequence("ATG", 35)
seq2 = Sequence("ATGCT", 30)

print(seq1.seq, seq1.qual, seq1.len, seq1.tissue)
print(seq2.seq, seq2.qual, seq2.len, seq2.tissue)

### Adding a method: `reverse_complement`

A **method** is just a function defined inside a class. It automatically receives the
instance it was called on as its first argument, conventionally named `self`.

In [8]:
class Sequence:
    tissue = "brain"

    def __init__(self, seq, quality):
        self.seq = seq
        self.qual = quality
        self.len = len(self.seq)

    def reverse_complement(self):
        complements = {"A": "T", "T": "A", "C": "G", "G": "C"}
        rc = ""
        for base in reversed(self.seq):
            rc = rc + complements[base]
        return rc

In [11]:
test_seq = Sequence("GATTACA", 35)
test_seq.reverse_complement()
#test_seq.len
test_seq.qual

35

### 🧪 Try it: step into a method with the debugger

Set a breakpoint on the `rc = rc + complements[base]` line inside `reverse_complement`
above (you'll need to re-run that class-definition cell with line numbers shown, and
put the breakpoint there). Then run the `test_seq.reverse_complement()` cell with the
debugger on.

- Use **Step Over** repeatedly and watch `rc` build up in the Variables panel, one
  character at a time, as `base` moves backwards through `self.seq`.
- This is exactly the same "accumulator" pattern (`rc = rc + something`) you've used
  before with `total = total + i` — seeing it happen inside an object method, with
  `self` visible in the Variables panel too, is a good way to demystify classes.

### Magic methods: `__str__` and `__add__`

Methods with double-underscores ("dunder") on both sides are special — Python calls
them automatically in certain situations. `__str__` controls what `print()` shows.
`__add__` controls what happens when you use `+` between two instances.

In [ ]:
class Sequence:
    tissue = "brain"

    def __init__(self, seq, quality):
        self.seq = seq
        self.qual = quality
        self.len = len(self.seq)

    def reverse_complement(self):
        complements = {"A": "T", "T": "A", "C": "G", "G": "C"}
        rc = ""
        for base in reversed(self.seq):
            rc = rc + complements[base]
        return rc

    def __str__(self):
        return f"Sequence: {self.seq}\nQuality: {self.qual}\nReverse complement: {self.reverse_complement()}"

    def __add__(self, other):
        combined_seq = self.seq + other.seq
        # length-weighted average quality
        combined_qual = (self.len * self.qual + other.len * other.qual) / (self.len + other.len)
        return Sequence(combined_seq, combined_qual)

In [ ]:
seq_a = Sequence("ACGT", 20)
seq_b = Sequence("GGGGGGGG", 30)

print(seq_a)          # uses __str__
print("---")
seq_c = seq_a + seq_b # uses __add__
print(seq_c)

### 🧪 Try it yourself
Add a method called `gc_content()` to the `Sequence` class (copy the class definition
below and extend it — don't just edit the cell above) that returns the GC content of
`self.seq` as a percentage, rounded to 1 decimal place (reuse your logic from the
Section 1 warm-up). Test it on a new instance.

In [ ]:
class Sequence:
    tissue = "brain"

    def __init__(self, seq, quality):
        self.seq = seq
        self.qual = quality
        self.len = len(self.seq)

    def reverse_complement(self):
        complements = {"A": "T", "T": "A", "C": "G", "G": "C"}
        rc = ""
        for base in reversed(self.seq):
            rc = rc + complements[base]
        return rc

    def gc_content(self):
        # Your code here
        pass

    def __str__(self):
        return f"Sequence: {self.seq}\nQuality: {self.qual}"


my_seq = Sequence("ATGCGGATCCTTAACGGGCTA", 33)
my_seq.gc_content()

## 11. Handling Bad Data with `try` / `except`

Real data is messy — an unexpected character, a missing file, a divide-by-zero. Rather
than letting your whole program crash, you can catch the error and decide what to do.

In [12]:
def try_it(num1, num2):
    try:
        result = num1 / num2
    except Exception as e:
        print("Something went wrong:", e)
    
    print("...but the program kept going!")
    
try_it(10, 0)

Something went wrong: division by zero
...but the program kept going!

### A biological example: invalid bases

Our `reverse_complement` method will crash with a `KeyError` if the sequence contains
a character that isn't `A`, `T`, `C`, or `G` (like `N`, which represents an unknown
base in real sequencing data). Let's catch that, and use `continue` — from the intro
course — to skip bad sequences instead of stopping entirely.

In [14]:
raw_sequences = ["ATGC", "GGCAT", "ATNGC", "CCGGA", "TTXAA"]

good_sequences = []
skipped = []

for s in raw_sequences:
    try:
        seq_obj = Sequence(s, 30)
        seq_obj.reverse_complement()   # will raise KeyError for 'N' or 'X'
        good_sequences.append(s)
    except KeyError as e:
        skipped.append((s, str(e)))
        continue

print("Good sequences:", good_sequences)
print("Skipped:", skipped)

NameError: name 'Sequence' is not defined

### 🧪 Try it yourself
Using the same `raw_sequences` list, count how many sequences were skipped, and print
a one-line summary like: `"3 of 5 sequences were valid."`

In [ ]:
# Your code here

## 12. Final Mini-Project: A Small Sequence-Analysis Pipeline

Time to combine (almost) everything: **classes**, **dictionaries**, **functions**,
**for loops**, **try/except**, and **watching your data types**. This mirrors a
realistic (tiny!) bioinformatics workflow: take a batch of reads, clean/validate them,
build `Sequence` objects, and report which TF motifs each one contains.

In [ ]:
raw_reads = {
    "read1": "ATGCGGATCCTTAACGGGCTA",
    "read2": "GGGCCATTAGCATGACGGTTA",
    "read3": "TTACGATCGATCGGGCTAATT",
    "read4": "ATNCGATCGATCGGGCTAATT",   # contains an invalid base -- should be skipped
}

motifs = {
    "CEBPD": "ATGC",
    "BRCA1": "CAGA",
    "ATF1": "ATCC",
    "IRF1": "ATTAACC",
}

def get_hits(in_seq, motif_dict):
    """Return a list of gene names whose motif is found in in_seq."""
    seq_upper = in_seq.upper()
    return [gene for gene, motif in motif_dict.items() if motif in seq_upper]


read_objects = {}
for name, raw_seq in raw_reads.items():
    try:
        read_objects[name] = Sequence(raw_seq, quality=30)
        read_objects[name].reverse_complement()   # validates the bases as a side effect
    except KeyError:
        print(f"{name}: contains an invalid base, skipping.")
        continue

print("=== Motif Report ===")
for name, seq_obj in read_objects.items():
    hits = get_hits(seq_obj.seq, motifs)
    print(f"{name}: length={seq_obj.len}, motifs found={hits}")

### 🧪 Final challenge

Extend the pipeline above:
1. Add your own `read5` to `raw_reads` with a sequence containing at least one motif
   from `motifs`.
2. For each valid read, also compute and print its GC content (reuse the method you
   wrote in Section 10, or write the logic inline).
3. Use the JupyterLab debugger: set a breakpoint inside the `for name, seq_obj in
   read_objects.items():` loop and step through, watching `name`, `seq_obj`, and `hits`
   change in the Variables panel for each read.

This exercise intentionally has no starter code — build it from what you've learned
today and in the intro course. Good luck!

In [ ]:
# Your final challenge code here

## Congratulations! 🎉

In this course you added a whole new toolkit on top of the intro course:
- **The JupyterLab visual debugger** — a point-and-click way to step through code
- **Watching data types as you iterate** — especially with dictionaries, views, and
  iterators, where the "obvious" type is often not what you get
- **Tuples and sets**, and where each one naturally shows up
- **List comprehensions** for building lists compactly
- **String formatting and file I/O**
- **Classes**: attributes, methods, and the `__str__`/`__add__` magic methods
- **`try`/`except`** for handling messy real-world data gracefully

### Where to go next (Further Study)
The cells below are optional extensions, not part of the 3-hour core — read through
them whenever you're ready to go deeper.

---
## Further Study (Optional)

### Inheritance

Instead of one big `Sequence` class trying to handle DNA, RNA, and protein all at
once, you can create a general parent class and let more specific **subclasses**
inherit from it — adding or overriding only what's different.

In [ ]:
class GenericSequence:
    def __init__(self, sequence="", quality=0):
        self.sequence = sequence
        self.quality = quality

    def __str__(self):
        return f"Sequence: {self.sequence}\nQuality: {self.quality}"


class DNASequence(GenericSequence):    # DNASequence inherits from GenericSequence
    def __init__(self, sequence="", quality=0):
        if set(sequence.upper()) <= {"A", "C", "G", "T"}:
            super().__init__(sequence, quality)
        else:
            raise ValueError("Input sequence isn't valid DNA.")

    def transcribe(self):
        rna_complement = {"A": "U", "C": "G", "G": "C", "T": "A"}
        rna_seq = "".join(rna_complement[base] for base in reversed(self.sequence.upper()))
        return rna_seq


dna = DNASequence("ACCGGTC", 15)
print(dna)
print("Transcribed to RNA:", dna.transcribe())

### Custom iterators

Any class can define `__iter__` and `__next__` methods to control exactly how a `for`
loop iterates over its instances — this is what's happening "under the hood" every
time you write `for x in some_list:` or `for line in some_file:`. Try stepping through
this with the debugger to see `__next__` get called once per loop iteration.

In [ ]:
class Countdown:
    def __init__(self, start):
        self.current = start

    def __iter__(self):
        return self

    def __next__(self):
        if self.current <= 0:
            raise StopIteration
        value = self.current
        self.current -= 1
        return value


for n in Countdown(5):
    print(n)

### Saving objects to disk: `pickle` and `shelve`

- `pickle` saves a single Python object (list, dict, your own class instance) to a
  binary file, and loads it back exactly as it was.
- `shelve` works like a dictionary that's backed by a file on disk, so you can store
  several named objects and reload just the ones you need.

Both are worth exploring once your datasets or object collections get large enough
that recomputing them every time becomes slow.